// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTTrCumgRkzGWPPiq4CBvZM1Cm0TMYh8',
    appId: '1:455618070118:web:1f89305008b54df1b48fa7',
    messagingSenderId: '455618070118',
    projectId: 'auth1-55e74',
    authDomain: 'auth1-55e74.firebaseapp.com',
    storageBucket: 'auth1-55e74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZbzp0H2nmDxr69014fcViCGgnluAev4',
    appId: '1:455618070118:android:26ea783bec22a913b48fa7',
    messagingSenderId: '455618070118',
    projectId: 'auth1-55e74',
    storageBucket: 'auth1-55e74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjIRhdGzOsVune2ANtJM8b6vdkp92YzuI',
    appId: '1:455618070118:ios:31ed6ddb70a7afd7b48fa7',
    messagingSenderId: '455618070118',
    projectId: 'auth1-55e74',
    storageBucket: 'auth1-55e74.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjIRhdGzOsVune2ANtJM8b6vdkp92YzuI',
    appId: '1:455618070118:ios:31ed6ddb70a7afd7b48fa7',
    messagingSenderId: '455618070118',
    projectId: 'auth1-55e74',
    storageBucket: 'auth1-55e74.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJTTrCumgRkzGWPPiq4CBvZM1Cm0TMYh8',
    appId: '1:455618070118:web:fe1b0fe17d5afa25b48fa7',
    messagingSenderId: '455618070118',
    projectId: 'auth1-55e74',
    authDomain: 'auth1-55e74.firebaseapp.com',
    storageBucket: 'auth1-55e74.firebasestorage.app',
  );
}
